!function(e){var t={};function r(n){if(t[n])return t[n].exports;var c=t[n]={i:n,l:!1,exports:{}};return e[n].call(c.exports,c,c.exports,r),c.l=!0,c.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var c in e)r.d(n,c,function(t){return e[t]}.bind(null,c));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _select__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./select */ "./src/js/select.js");\n\nObject(_select__WEBPACK_IMPORTED_MODULE_0__["select"])();\nvar burger = document.querySelector(".adap__link");\nburger.addEventListener("click", function (event) {\n  event.preventDefault; //   burger.classList.toggle("_active-burger");\n\n  document.querySelector(".burger").classList.toggle("_active__burger");\n  document.querySelector(".canvas").classList.toggle("_active__burger");\n});\n\nwindow.onresize = function () {\n  if (window.matchMedia("screen and (min-width:778px)").matches) {\n    document.querySelector(".burger").classList.remove("_active__burger");\n    document.querySelector(".canvas").classList.remove("_active__burger");\n    burger.classList.remove("_active__burger");\n  } else {}\n};\n\n//# sourceURL=webpack:///./src/js/main.js?')},"./src/js/select.js":
/*!**************************!*\
  !*** ./src/js/select.js ***!
  \**************************/
/*! exports provided: select */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "select", function() { return select; });\nvar select = function select() {\n  var selectHeader = document.querySelectorAll(".select__header");\n  var selectItem = document.querySelectorAll(".select__item");\n  selectHeader.forEach(function (item) {\n    item.addEventListener("click", selectToggle);\n  });\n  selectItem.forEach(function (item) {\n    item.addEventListener("click", selectChoose);\n  });\n\n  function selectToggle() {\n    this.parentElement.classList.toggle("isActive");\n  }\n\n  function selectChoose() {\n    var text = this.innerText;\n    var closeSelect = this.closest(".select");\n    var cuurentText = closeSelect.querySelector(".select__current");\n    cuurentText.innerText = text;\n    closeSelect.classList.remove("isActive");\n  }\n};\n\n//# sourceURL=webpack:///./src/js/select.js?')}});
//# sourceMappingURL=main.js.map
