!function(e){var t={};function n(r){if(t[r])return t[r].exports;var c=t[r]={i:r,l:!1,exports:{}};return e[r].call(c.exports,c,c.exports,n),c.l=!0,c.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var c in e)n.d(r,c,function(t){return e[t]}.bind(null,c));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/main.js")}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _select__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./select */ "./src/js/select.js");\n\nObject(_select__WEBPACK_IMPORTED_MODULE_0__["select"])();\n\n//# sourceURL=webpack:///./src/js/main.js?')},"./src/js/select.js":
/*!**************************!*\
  !*** ./src/js/select.js ***!
  \**************************/
/*! exports provided: select */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "select", function() { return select; });\nvar select = function select() {\n  var selectHeader = document.querySelectorAll(".select__header");\n  var selectItem = document.querySelectorAll(".select__item");\n  selectHeader.forEach(function (item) {\n    item.addEventListener("click", selectToggle);\n  });\n  selectItem.forEach(function (item) {\n    item.addEventListener("click", selectChoose);\n  });\n\n  function selectToggle() {\n    this.parentElement.classList.toggle("isActive");\n  }\n\n  function selectChoose() {\n    var text = this.innerText;\n    var closeSelect = this.closest(".select");\n    var cuurentText = closeSelect.querySelector(".select__current");\n    cuurentText.innerText = text;\n    closeSelect.classList.remove("isActive");\n  }\n};\n\n//# sourceURL=webpack:///./src/js/select.js?')}});
//# sourceMappingURL=main.js.map
